### ISSUE TITLE
pacman.tags no longer set 

### ISSUE THREAD

**Issue by doanac** [foundriesio/lmp-device-register#43]
It seems the refactor somehow dropped the saving of the `pacman.tags` variable in sota.toml. This leaves a device unable to check in and get its TUF metadata.

**Comment by doanac** [comment]
@mwasilew - FYI. You may hit this soon.

**Comment by doanac** [comment]
Your refactor seems to be based on older code that didn't have this - https://github.com/foundriesio/lmp-device-register/commit/9a59286fbe3298d1fe196792fd1a3101ab0032fe

**Comment by ldts** [comment]
if it is easy to test for you, can you just remove the check from L160? or define AKLITE_TAGS at the top of the file? maybe is just a leftover

**Comment by vkhoroz** [comment]
@ldts this is not just about the tag parameter.

The primary goal of the change @doanac mentioned is to read the factory name and tags from `/etc/os-release`.
Without that change the _Fast First Build_ feature becomes non-functional, as well as other use cases.

**Comment by ldts** [comment]
> @ldts this is not just about the tag parameter.
> 
> The primary goal of the change @doanac mentioned is to read the factory name and tags from `/etc/os-release`. Without that change the _Fast First Build_ feature becomes non-functional, as well as other use cases.

but of course. what I am saying is that I believe all of that is taking care of further down. So we can test and check -since is a simple change- and if code is missing I can then review.

if doing a one line change and executing a command is harder than reading the update software then we have a problem....

**Comment by ldts** [comment]
> So, I _believe_ you're right and we're fine to simply remove the ifdef.

yeah I think so tool - I checked the code and it seems to be all there. 

I just sent a PR anyways - the #ifdef is wrong independently if it fixes the issue or not  (just that I cant merge because I dont have write access to this repository).
