### ISSUE TITLE
Improve Error Handling for Device Registration by Enforcing Explicit Factory Flag

### ISSUE THREAD

**Issue by camilamacedo86** [foundriesio/lmp-device-register#59]
## Description

If we try to register a device without informing the factory (`sudo lmp-device-register `) flag, it fails with `Error authorizing device: 'scope' parameter is not valid: ` which leads the user to think that there is some permission issue. See:

```
~$ sudo lmp-device-register                           
Password: 
Tag read from /etc/os-release
Factory read from /etc/os-release
UUID: 66f9390d-d404-4693-83d7-2ec9ed094e6b [Random]
Setting factory name to UUID 
PID memory locked
Foundries providing auth token 

----------------------------------------------------------------------------
Visit the link below in your browser to authorize this new device. This link
will expire in 15 minutes.
  Device Name: 66f9390d-d404-4693-83d7-2ec9ed094e6b
  User code: 36a0-06b3
  Browser URL: https://app.foundries.io/activate/

Error authorizing device: 'scope' parameter is not valid: wrong Factory value, or you are not a member of the Factory
```

## What would you expected instead

Since the value is required for the operation, I would expect the need to be explicit, and the command should fail if/when the flag is not informed.

**Comment by ricardosalveti** [comment]
I think this is fixed with https://github.com/foundriesio/lmp-device-register/pull/53, which is not yet part of a release.

**Comment by camilamacedo86** [comment]
Cool, so I am closing this one.
